routes/web.php
<?php

use App\Http\Controllers\AspectController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OwnerController;
use App\Http\Controllers\StandardController;
use Illuminate\Support\Facades\Route;


/* Auth::routes(); */
/* Autenticacion */
    /* Iniciar sesion */
    Route::get('/login',[LoginController::class,'showLoginForm'])->middleware('guest')->name('login');
    Route::post('/login',[LoginController::class,'login'])->middleware('guest'); 
    /* Cerrar sesion */
    Route::post('/logout',[LoginController::class,'logout'])->middleware('auth')->name('logout'); 
    /* Enviar correo recuperar contraseña */
    Route::get('/password/reset',[ForgotPasswordController::class,'showLinkRequestForm'])->name('password.request');
    Route::post('/password/email',[ForgotPasswordController::class,'sendResetLinkEmail'])->name('password.email');
    /* Restablecer contraseña */
    Route::get('/password/reset/{token}',[ResetPasswordController::class,'showResetForm'])->name('password.reset');
    Route::post('/password/reset',[ResetPasswordController::class,'reset'])->name('password.update');
/* Fin Autenticacion */

/* Rutas Protegidas Con Auth */
    Route::middleware(['auth'])->group(function(){
        Route::middleware(['password.changed'])->group(function(){
            /* Panel pricipal */
            Route::get('/',[DashboardController::class,'index'])->name('dashboard.index');
            /* Usuarios */
            Route::resource('/users',UserController::class)->except('show')->names('users');
            /* Dueños */
            Route::resource('/owners',OwnerController::class)->except('show')->names('owners');
            /* Criterios */
            Route::resource('/standards',StandardController::class)->names('standards');
            /* Aspectos */
            Route::resource('/aspects',AspectController::class)->only(['store','update','destroy'])->names('aspects');
        });
        /* datos del perfil */
        Route::get('/profile',[ProfileController::class,'index'])->name('profile.index');
        Route::put('/profile/password',[ProfileController::class,'changePassword'])->name('profile.password');
        Route::post('/profile/avatar',[ProfileController::class,'avatar'])->name('profile.avatar');
    });
/* Fin Rutas Protegidas Con Auth */

app/Models/User/Traits/UserMutators.php
<?php

namespace App\Models\User\Traits;
use App\Models\User;

trait UserMutators {
    /* setters */
    public function setNameAttribute($value)
    {
        $this->attributes['name'] = strtolower($value);
    }
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

}

app/Models/User/Traits/UserRelationship.php
<?php

namespace App\Models\User\Traits;
use App\Models\User;

trait UserRelationship {
    
}

app/Models/User/User.php
<?php

namespace App\Models\User;

/* Traits */
use App\Models\User\Traits\UserMutators;
use App\Models\User\Traits\UserRelationship;
/* paquetes */
use Spatie\Permission\Traits\HasRoles;
use Cviebrock\EloquentSluggable\Sluggable;
/* illuminate */
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory,
        Notifiable,
        HasRoles,
        Sluggable,
        UserMutators,
        UserRelationship;

    protected $fillable = [
        'name',
        'slug',
        'email',
        'avatar',
        'password',
        'password_changed',
    ];
    protected $hidden = [
        'password',
        'remember_token',
    ];
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function getRouteKeyName()
    {
        return 'slug';
    }
    public function sluggable(): array
    {
        return ['slug' => ['source' => 'name']];
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
/* modelos */
use App\Models\User\User;
/* request */
use App\Http\Requests\User\UserStoreRequest;
use App\Http\Requests\User\UserUpdateRequest;
/* correos */
use App\Mail\User\RegisterUser;
use Illuminate\Support\Facades\Mail;
/* paquetes */
use Spatie\Permission\Models\Role;
/* Illuminate */
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /* Constructor */
    public function __construct()
    {
        $this->middleware('can:users.index')->only('index');
        $this->middleware('can:users.create')->only(['create','store']);
        $this->middleware('can:users.update')->only(['edit','update']);
        $this->middleware('can:users.destroy')->only('destroy');
    }
    /* Crud */
    public function index()
    {
        $users = User::where('id','!=',Auth::id())->get();
        return view('users.index',compact('users'));
    }
    public function create()
    {
        $roles = Role::where('name','!=','super-admin')->orderBy('name','ASC')->get();
        return view('users.create',compact('roles'));
    }
    public function store(UserStoreRequest $request)
    {
        /* Crear usuario */
        $user = User::make( $request->all() );
        /* Contraseña */
        $password = substr(str_shuffle("0123456789abcdefghijklmnñopqrstvwxyz+-@"), 0, 12);
        $user->password = $password;
        $user->save();
        /* Asignar rol */
        $user->assignRole($request->role);
        /* Email */
        $mail = new RegisterUser($user,$password);
        Mail::to('angel@gmail.com')->send($mail);
        /* Return */
        return redirect()->route('users.index')->with(['message' => 'Registro almacenado con éxito']);
    }
    public function edit(User $user)
    {
        $roles = Role::where('name','!=','super-admin')->orderBy('name','ASC')->get();
        return view('users.edit',compact('roles','user'));
    }
    public function update(UserUpdateRequest $request, User $user)
    {
        $user->update( $request->all() );
        $user->syncRoles($request->role);
        return redirect()->route('users.index')->with(['message' => 'Registro actualizado con éxito']);
    }
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('users.index')->with(['message' => 'Registro eliminado con éxito']);
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('icon')
    <i class="pe-7s-user icon-gradient bg-sunny-morning"></i>
@endsection

@section('title')
    Registrar usuario
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Lista de usuarios</a></li>
    <li class="active breadcrumb-item" aria-current="page">Registrar usuario</li>
@endsection

@section('button_title')
    <a href="{{ route('users.index') }}" type="button" data-toggle="tooltip" title="" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary" data-original-title="Regresar" aria-describedby="tooltip109285">
        <i class="fa fa-arrow-left"></i>
    </a>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form class="form-row" action="{{ route('users.store') }}" method="POST">
                    @csrf
                    @include('users.partials.form')
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('icon')
    <i class="pe-7s-user icon-gradient bg-sunny-morning"></i>
@endsection

@section('title')
    Actualizar usuario
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Lista de usuarios</a></li>
    <li class="active breadcrumb-item" aria-current="page">Actualizar usuario</li>
@endsection

@section('button_title')
    <a href="{{ route('users.index') }}" type="button" data-toggle="tooltip" title="" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary" data-original-title="Regresar" aria-describedby="tooltip109285">
        <i class="fa fa-arrow-left"></i>
    </a>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form class="form-row" action="{{ route('users.update',$user) }}" method="POST">
                    @csrf
                    @method('PUT')
                    @include('users.partials.form')
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('icon')
    <i class="pe-7s-users icon-gradient bg-sunny-morning"></i>
@endsection

@section('title')
    Lista de usuarios
@endsection

@section('button_title')
    <a href="{{ route('users.create') }}" type="button" data-toggle="tooltip" title="" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary" data-original-title="Agregar" aria-describedby="tooltip109285">
        <i class="fa fa-plus"></i>
    </a>
@endsection

@section('breadcrumb')
    <li class="active breadcrumb-item" aria-current="page">Lista de usuarios</li>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table" id="table-index">
                        <thead class="text-light bg-primary">
                            <tr>
                                <th>Nombre</th>
                                <th>Correo</th>
                                <th>Creado</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $item)
                                <tr>
                                    <td>{{$item->name}}</td>
                                    <td>{{$item->email}}</td>
                                    <td>{{$item->created_at->format('d-m-Y')}}</td>
                                    <td><a data-toggle="tooltip" title="Editar" class="btn btn-sm btn-warning" href="{{ route('users.edit', $item) }}"><i class="fa fa-edit"></i></a></td>
                                    <td><button data-toggle="tooltip" title="Eliminar" class="btn btn-sm btn-outline-danger" onclick="deleteItem('{{$item->slug}}')"><i class="fa fa-trash"></i></button></td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <form action="" method="post" id="form-delete-item">
        @csrf @method('DELETE')
    </form>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('js/jquery-3.5.1.js') }}"></script>
    <script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#table-index').DataTable();
        } );
    </script>
    <script>
        function deleteItem(item)
        {
            swal({
                    title: "¿Eliminar registro?",
                    text: "¿Esta seguro que desea eliminar este registro?",
                    icon: "warning",
                    buttons: ['Cancelar','Eliminar'],
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        document.querySelector("#form-delete-item").action = window.location.origin + '/users/' + item
                        document.querySelector("#form-delete-item").submit()
                    }
                })
        }
    </script>
@endsection

@section('styles')
    <link href="{{asset('css/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
@endsection