routes/web.php
<?php

use App\Http\Controllers\AspectController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OwnerController;
use App\Http\Controllers\StandardController;
use Illuminate\Support\Facades\Route;


/* Auth::routes(); */
/* Autenticacion */
    /* Iniciar sesion */
    Route::get('/login',[LoginController::class,'showLoginForm'])->middleware('guest')->name('login');
    Route::post('/login',[LoginController::class,'login'])->middleware('guest'); 
    /* Cerrar sesion */
    Route::post('/logout',[LoginController::class,'logout'])->middleware('auth')->name('logout'); 
    /* Enviar correo recuperar contraseña */
    Route::get('/password/reset',[ForgotPasswordController::class,'showLinkRequestForm'])->name('password.request');
    Route::post('/password/email',[ForgotPasswordController::class,'sendResetLinkEmail'])->name('password.email');
    /* Restablecer contraseña */
    Route::get('/password/reset/{token}',[ResetPasswordController::class,'showResetForm'])->name('password.reset');
    Route::post('/password/reset',[ResetPasswordController::class,'reset'])->name('password.update');
/* Fin Autenticacion */

/* Rutas Protegidas Con Auth */
    Route::middleware(['auth'])->group(function(){
        Route::middleware(['password.changed'])->group(function(){
            /* Panel pricipal */
            Route::get('/',[DashboardController::class,'index'])->name('dashboard.index');
            /* Usuarios */
            Route::resource('/users',UserController::class)->except('show')->names('users');
            /* Dueños */
            Route::resource('/owners',OwnerController::class)->except('show')->names('owners');
            /* Criterios */
            Route::resource('/standards',StandardController::class)->names('standards');
            /* Aspectos */
            Route::resource('/aspects',AspectController::class)->only(['store','update','destroy'])->names('aspects');
        });
        /* datos del perfil */
        Route::get('/profile',[ProfileController::class,'index'])->name('profile.index');
        Route::put('/profile/password',[ProfileController::class,'changePassword'])->name('profile.password');
        Route::post('/profile/avatar',[ProfileController::class,'avatar'])->name('profile.avatar');
    });
/* Fin Rutas Protegidas Con Auth */

app/Models/Owner/Owner.php
<?php

namespace App\Models\Owner;

/* Traits */
use App\Models\Owner\Traits\OwnerMutators;
use App\Models\Owner\Traits\OwnerRelationship;
/* paquetes */
use Cviebrock\EloquentSluggable\Sluggable;
/* illuminate */
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Owner extends Model
{
    use HasFactory,
        Sluggable,
        OwnerMutators,
        OwnerRelationship;

    protected $fillable = [
        'name',
        'slug',
    ];
    public function getRouteKeyName()
    {
        return 'slug';
    }
    public function sluggable(): array
    {
        return ['slug' => ['source' => 'name']];
    }
}

app/Models/Owner/Traits/OwnerMutators.php
<?php

namespace App\Models\Owner\Traits;

trait OwnerMutators {
    /* setters */
    public function setNameAttribute($value)
    {
        $this->attributes['name'] = strtolower($value);
    }
}

app/Models/Owner/Traits/OwnerRelationship.php
<?php

namespace App\Models\Owner\Traits;

trait OwnerRelationship {

}

app/Http/Controllers/OwnerController.php
<?php

namespace App\Http\Controllers;

/* modelos */
use App\Models\Owner\Owner;
/* request */
use App\Http\Requests\Owner\OwnerStoreRequest;
use App\Http\Requests\Owner\OwnerUpdateRequest;
/* paquetes */
use Spatie\Permission\Models\Role;

class OwnerController extends Controller
{
    /* Constructor */
    public function __construct()
    {
        $this->middleware('can:owners.index')->only('index');
        $this->middleware('can:owners.create')->only(['create','store']);
        $this->middleware('can:owners.update')->only(['edit','update']);
        $this->middleware('can:owners.destroy')->only('destroy');
    }
    /* Crud */
    public function index()
    {
        $owners = Owner::get();
        return view('owners.index',compact('owners'));
    }
    public function create()
    {
        return view('owners.create');
    }
    public function store(OwnerStoreRequest $request)
    {
        $owner = Owner::create( $request->all() );
        /* Return */
        return redirect()->route('owners.index')->with(['message' => 'Registro almacenado con éxito']);
    }
    public function edit(Owner $owner)
    {
        return view('owners.edit',compact('owner'));
    }
    public function update(OwnerUpdateRequest $request, Owner $owner)
    {
        $owner->update( $request->all() );
        return redirect()->route('owners.index')->with(['message' => 'Registro actualizado con éxito']);
    }
    public function destroy(Owner $owner)
    {
        $owner->delete();
        return redirect()->route('owners.index')->with(['message' => 'Registro eliminado con éxito']);
    }
}

resources/views/owners/create.blade.php
@extends('layouts.app')

@section('icon')
    <i class="pe-7s-user icon-gradient bg-sunny-morning"></i>
@endsection

@section('title')
    Registrar dueño
@endsection

@section('button_title')
    <a href="{{ route('owners.index') }}" type="button" data-toggle="tooltip" title="" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary" data-original-title="Regresar" aria-describedby="tooltip109285">
        <i class="fa fa-arrow-left"></i>
    </a>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('owners.index') }}">Lista de dueños</a></li>
    <li class="active breadcrumb-item" aria-current="page">Registrar dueño</li>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form class="form-row" action="{{ route('owners.store') }}" method="POST">
                        @csrf
                        @include('owners.partials.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/owners/edit.blade.php
@extends('layouts.app')

@section('icon')
    <i class="pe-7s-user icon-gradient bg-sunny-morning"></i>
@endsection

@section('title')
    Actualizar usuario
@endsection

@section('button_title')
    <a href="{{ route('owners.index') }}" type="button" data-toggle="tooltip" title="" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary" data-original-title="Regresar" aria-describedby="tooltip109285">
        <i class="fa fa-arrow-left"></i>
    </a>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('owners.index') }}">Lista de dueños</a></li>
    <li class="active breadcrumb-item" aria-current="page">Actualizar dueño</li>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form class="form-row" action="{{ route('owners.update',$owner) }}" method="POST">
                        @csrf
                        @method('PUT')
                        @include('owners.partials.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/owners/index.blade.php
@extends('layouts.app')

@section('icon')
    <i class="pe-7s-users icon-gradient bg-sunny-morning"></i>
@endsection

@section('title')
    Lista de dueños
@endsection

@section('button_title')
    <a href="{{ route('owners.create') }}" type="button" data-toggle="tooltip" title="" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary" data-original-title="Agregar" aria-describedby="tooltip109285">
        <i class="fa fa-plus"></i>
    </a>
@endsection

@section('breadcrumb')
    <li class="active breadcrumb-item" aria-current="page">Lista de dueños</li>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table" id="table-index">
                        <thead class="text-light bg-primary">
                            <tr>
                                <th>Nombre</th>
                                <th>Creado</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($owners as $item)
                                <tr>
                                    <td>{{$item->name}}</td>
                                    <td>{{$item->created_at->format('d-m-Y')}}</td>
                                    <td><a data-toggle="tooltip" title="Editar" class="btn btn-sm btn-warning" href="{{ route('owners.edit', $item) }}"><i class="fa fa-edit"></i></a></td>
                                    <td><button data-toggle="tooltip" title="Eliminar" class="btn btn-sm btn-outline-danger" onclick="deleteItem('{{$item->slug}}')"><i class="fa fa-trash"></i></button></td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <form action="" method="post" id="form-delete-item">
        @csrf @method('DELETE')
    </form>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('js/jquery-3.5.1.js') }}"></script>
    <script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#table-index').DataTable();
        } );
    </script>
    <script>
        function deleteItem(item)
        {
            swal({
                    title: "¿Eliminar registro?",
                    text: "¿Esta seguro que desea eliminar este registro?",
                    icon: "warning",
                    buttons: ['Cancelar','Eliminar'],
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        document.querySelector("#form-delete-item").action = window.location.origin + '/owners/' + item
                        document.querySelector("#form-delete-item").submit()
                    }
                })
        }
    </script>
@endsection

@section('styles')
    <link href="{{asset('css/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
@endsection