routes/web.php
<?php

use App\Http\Controllers\AspectController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OwnerController;
use App\Http\Controllers\StandardController;
use Illuminate\Support\Facades\Route;


/* Auth::routes(); */
/* Autenticacion */
    /* Iniciar sesion */
    Route::get('/login',[LoginController::class,'showLoginForm'])->middleware('guest')->name('login');
    Route::post('/login',[LoginController::class,'login'])->middleware('guest'); 
    /* Cerrar sesion */
    Route::post('/logout',[LoginController::class,'logout'])->middleware('auth')->name('logout'); 
    /* Enviar correo recuperar contraseña */
    Route::get('/password/reset',[ForgotPasswordController::class,'showLinkRequestForm'])->name('password.request');
    Route::post('/password/email',[ForgotPasswordController::class,'sendResetLinkEmail'])->name('password.email');
    /* Restablecer contraseña */
    Route::get('/password/reset/{token}',[ResetPasswordController::class,'showResetForm'])->name('password.reset');
    Route::post('/password/reset',[ResetPasswordController::class,'reset'])->name('password.update');
/* Fin Autenticacion */

/* Rutas Protegidas Con Auth */
    Route::middleware(['auth'])->group(function(){
        Route::middleware(['password.changed'])->group(function(){
            /* Panel pricipal */
            Route::get('/',[DashboardController::class,'index'])->name('dashboard.index');
            /* Usuarios */
            Route::resource('/users',UserController::class)->except('show')->names('users');
            /* Dueños */
            Route::resource('/owners',OwnerController::class)->except('show')->names('owners');
            /* Criterios */
            Route::resource('/standards',StandardController::class)->names('standards');
            /* Aspectos */
            Route::resource('/aspects',AspectController::class)->only(['store','update','destroy'])->names('aspects');
        });
        /* datos del perfil */
        Route::get('/profile',[ProfileController::class,'index'])->name('profile.index');
        Route::put('/profile/password',[ProfileController::class,'changePassword'])->name('profile.password');
        Route::post('/profile/avatar',[ProfileController::class,'avatar'])->name('profile.avatar');
    });
/* Fin Rutas Protegidas Con Auth */

resources/views/commons/footer.blade.php
<div class="app-wrapper-footer">
    <div class="app-footer">
        <div class="app-footer__inner">
            <div class="app-footer-left">
                <ul class="nav">
                    <li class="nav-item">
                        <a href="javascript:void(0);" class="nav-link">
                            Footer Link 1
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="javascript:void(0);" class="nav-link">
                            Footer Link 2
                        </a>
                    </li>
                </ul>
            </div>
            <div class="app-footer-right">
                <ul class="nav">
                    <li class="nav-item">
                        <a href="javascript:void(0);" class="nav-link">
                            Footer Link 3
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="javascript:void(0);" class="nav-link">
                            <div class="badge badge-success mr-1 ml-0">
                                <small>NEW</small>
                            </div>
                            Footer Link 4
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

resources/views/commons/navbar.blade.php
<div class="app-header header-shadow  header-text-light" style="background-color: #0cc2ff;">
    <div class="app-header__logo">
        <img class="mx-auto" src="{{ asset('theme/assets/images/logo-inverse.png') }}" alt="">
        <div class="header__pane ml-auto">
            <div>
                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <div class="app-header__mobile-menu">
        <div>
            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
        </div>
    </div>
    <div class="app-header__menu">
        <span>
            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                <span class="btn-icon-wrapper">
                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                </span>
            </button>
        </span>
    </div>    
    <div class="app-header__content">
        <div class="app-header-right">
            <div class="header-btn-lg pr-0">
                <div class="widget-content p-0">
                    <div class="widget-content-wrapper">
                        <div class="widget-content-left">
                            <div class="btn-group">
                                <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
                                    <img width="42" class="rounded-circle" src="https://via.placeholder.com/42" alt="image-profile">
                                    <i class="fa fa-angle-down ml-2 opacity-8"></i>
                                </a>
                                <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu dropdown-menu-right">
                                    <a href="{{ route('profile.index') }}" type="button" tabindex="0" class="dropdown-item">Mi Perfil</a>
                                    {{-- Cerrar Sesion --}}
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Cerrar Sesión') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                    {{-- Fin cerrar sesion --}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>        
        </div>
    </div>
</div>

resources/views/commons/sidebar.blade.php
<div class="app-sidebar sidebar-shadow  sidebar-text-light" style="background-color: #faa635">
    <div class="app-header__logo">
        <div class="logo-src"></div>
        <div class="header__pane ml-auto">
            <div>
                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <div class="app-header__mobile-menu">
        <div>
            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
        </div>
    </div>
    <div class="app-header__menu">
        <span>
            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                <span class="btn-icon-wrapper">
                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                </span>
            </button>
        </span>
    </div>    
    <div class="scrollbar-sidebar ps ps--active-y">
        <div class="app-sidebar__inner">
            <ul class="vertical-nav-menu metismenu">
                <li class="app-sidebar__heading">Panel Principal</li>
                <li>
                    <a href="{{ route('dashboard.index') }}">
                        <i class="metismenu-icon pe-7s-monitor"></i>
                        Panel Principal
                    </a>
                </li>
                <li class="app-sidebar__heading">Administración</li>
                {{-- Usuarios --}}
                <li>
                    <a href="#">
                        <i class="metismenu-icon pe-7s-users"></i>
                        Usuarios
                        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                    </a>
                    <ul class="mm-collapse">
                        <li>
                            <a href="{{ route('users.index') }}"> <i class="pe-7s-note2"></i> Lista de usuarios </a>
                        </li>
                        <li>
                            <a href="{{ route('users.create') }}"> <i class="pe-7s-plus"></i> Registrar usuario </a>
                        </li>
                    </ul>
                </li>
                <li class="app-sidebar__heading">Programas</li>
                {{-- Dueños --}}
                <li>
                    <a href="#">
                        <i class="metismenu-icon pe-7s-id"></i>
                        Dueños
                        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                    </a>
                    <ul class="mm-collapse">
                        <li>
                            <a href="{{ route('owners.index') }}"> <i class="pe-7s-note2"></i> Lista de dueños </a>
                        </li>
                        <li>
                            <a href="{{ route('owners.create') }}"> <i class="pe-7s-plus"></i> Registrar dueño </a>
                        </li>
                    </ul>
                </li>
                {{-- Dueños --}}
                <li>
                    <a href="#">
                        <i class="metismenu-icon pe-7s-star"></i>
                        Criterios
                        <i class="metismenu-state-icon pe-7s-angle-down caret-left"></i>
                    </a>
                    <ul class="mm-collapse">
                        <li>
                            <a href="{{ route('standards.index') }}"> <i class="pe-7s-note2"></i> Lista de criterios </a>
                        </li>
                        <li>
                            <a href="{{ route('standards.create') }}"> <i class="pe-7s-plus"></i> Registrar criterio </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    <div class="ps__rail-x" style="left: 0px; bottom: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; height: 640px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 605px;"></div></div></div>
</div>