routes/web.php
<?php

use App\Http\Controllers\AspectController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OwnerController;
use App\Http\Controllers\StandardController;
use Illuminate\Support\Facades\Route;


/* Auth::routes(); */
/* Autenticacion */
    /* Iniciar sesion */
    Route::get('/login',[LoginController::class,'showLoginForm'])->middleware('guest')->name('login');
    Route::post('/login',[LoginController::class,'login'])->middleware('guest'); 
    /* Cerrar sesion */
    Route::post('/logout',[LoginController::class,'logout'])->middleware('auth')->name('logout'); 
    /* Enviar correo recuperar contraseña */
    Route::get('/password/reset',[ForgotPasswordController::class,'showLinkRequestForm'])->name('password.request');
    Route::post('/password/email',[ForgotPasswordController::class,'sendResetLinkEmail'])->name('password.email');
    /* Restablecer contraseña */
    Route::get('/password/reset/{token}',[ResetPasswordController::class,'showResetForm'])->name('password.reset');
    Route::post('/password/reset',[ResetPasswordController::class,'reset'])->name('password.update');
/* Fin Autenticacion */

/* Rutas Protegidas Con Auth */
    Route::middleware(['auth'])->group(function(){
        Route::middleware(['password.changed'])->group(function(){
            /* Panel pricipal */
            Route::get('/',[DashboardController::class,'index'])->name('dashboard.index');
            /* Usuarios */
            Route::resource('/users',UserController::class)->except('show')->names('users');
            /* Dueños */
            Route::resource('/owners',OwnerController::class)->except('show')->names('owners');
            /* Criterios */
            Route::resource('/standards',StandardController::class)->names('standards');
            /* Aspectos */
            Route::resource('/aspects',AspectController::class)->only(['store','update','destroy'])->names('aspects');
        });
        /* datos del perfil */
        Route::get('/profile',[ProfileController::class,'index'])->name('profile.index');
        Route::put('/profile/password',[ProfileController::class,'changePassword'])->name('profile.password');
        Route::post('/profile/avatar',[ProfileController::class,'avatar'])->name('profile.avatar');
    });
/* Fin Rutas Protegidas Con Auth */

app/Models/Standard/Standard.php
<?php

namespace App\Models\Standard;

/* Traits */
use App\Models\Standard\Traits\StandardMutators;
use App\Models\Standard\Traits\StandardRelationship;
/* paquetes */
use Cviebrock\EloquentSluggable\Sluggable;
/* illuminate */
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Standard extends Model
{
    use HasFactory,
        Sluggable,
        StandardMutators,
        StandardRelationship;

    protected $fillable = [
        'name',
        'slug',
        'description',
    ];
    public function getRouteKeyName()
    {
        return 'slug';
    }
    public function sluggable(): array
    {
        return ['slug' => ['source' => 'name']];
    }
}

app/Models/Standard/Traits/StandardMutators.php
<?php

namespace App\Models\Standard\Traits;

trait StandardMutators {
    /* setters */
    public function setNameAttribute($value)
    {
        $this->attributes['name'] = strtolower($value);
    }
}

app/Models/Standard/Traits/StandardRelationship.php
<?php

namespace App\Models\Standard\Traits;

use App\Models\Aspect\Aspect;

trait StandardRelationship {
    public function aspects()
    {
        return $this->hasMany(Aspect::class);
    }
}

app/Http/Controllers/StandardController.php
<?php

namespace App\Http\Controllers;

/* modelos */
use App\Models\Standard\Standard;
/* request */
use App\Http\Requests\Standard\StandardStoreRequest;
use App\Http\Requests\Standard\StandardUpdateRequest;
/* paquetes */
use Spatie\Permission\Models\Role;

class StandardController extends Controller
{
    /* Constructor */
    public function __construct()
    {
        $this->middleware('can:standards.index')->only('index');
        $this->middleware('can:standards.create')->only(['create','store']);
        $this->middleware('can:standards.update')->only(['edit','update']);
        $this->middleware('can:standards.destroy')->only('destroy');
    }
    /* Crud */
    public function index()
    {
        $standards = Standard::withCount('aspects')->get();
        return view('standards.index',compact('standards'));
    }
    public function create()
    {
        $roles = Role::where('name','!=','super-admin')->orderBy('name','ASC')->get();
        return view('standards.create',compact('roles'));
    }
    public function store(StandardStoreRequest $request)
    {
        $standard = Standard::create( $request->all() );
        /* Return */
        return redirect()->route('standards.index')->with(['message' => 'Registro almacenado con éxito']);
    }
    public function show(Standard $standard)
    {
        $standard->load('aspects');
        return view('standards.show',compact('standard'));
    }
    public function edit(Standard $standard)
    {
        return view('standards.edit',compact('standard'));
    }
    public function update(StandardUpdateRequest $request, Standard $standard)
    {
        $standard->update( $request->all() );
        return redirect()->route('standards.index')->with(['message' => 'Registro actualizado con éxito']);
    }
    public function destroy(Standard $standard)
    {
        $standard->delete();
        return redirect()->route('standards.index')->with(['message' => 'Registro eliminado con éxito']);
    }
}

resources/views/standards/create.blade.php
@extends('layouts.app')

@section('icon')
    <i class="pe-7s-star icon-gradient bg-sunny-morning"></i>
@endsection

@section('title')
    Registrar criterio
@endsection

@section('button_title')
    <a href="{{ route('standards.index') }}" type="button" data-toggle="tooltip" title="" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary" data-original-title="Regresar" aria-describedby="tooltip109285">
        <i class="fa fa-arrow-left"></i>
    </a>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('standards.index') }}">Lista de criterios</a></li>
    <li class="active breadcrumb-item" aria-current="page">Registrar criterio</li>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form class="form-row" action="{{ route('standards.store') }}" method="POST">
                        @csrf
                        @include('standards.partials.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/standards/edit.blade.php
@extends('layouts.app')

@section('icon')
    <i class="pe-7s-star icon-gradient bg-sunny-morning"></i>
@endsection

@section('title')
    Actualizar usuario
@endsection

@section('button_title')
    <a href="{{ route('standards.index') }}" type="button" data-toggle="tooltip" title="" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary" data-original-title="Regresar" aria-describedby="tooltip109285">
        <i class="fa fa-arrow-left"></i>
    </a>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('standards.index') }}">Lista de criterios</a></li>
    <li class="active breadcrumb-item" aria-current="page">Actualizar criterio</li>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form class="form-row" action="{{ route('standards.update',$standard) }}" method="POST">
                        @csrf
                        @method('PUT')
                        @include('standards.partials.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/standards/index.blade.php
@extends('layouts.app')

@section('icon')
    <i class="pe-7s-star icon-gradient bg-sunny-morning"></i>
@endsection

@section('title')
    Lista de criterios
@endsection

@section('button_title')
    <a href="{{ route('standards.create') }}" type="button" data-toggle="tooltip" title="" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary" data-original-title="Agregar" aria-describedby="tooltip109285">
        <i class="fa fa-plus"></i>
    </a>
@endsection

@section('breadcrumb')
    <li class="active breadcrumb-item" aria-current="page">Lista de criterios</li>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table" id="table-index">
                        <thead class="text-light bg-primary">
                            <tr>
                                <th>Nombre</th>
                                <th>Aspectos</th>
                                <th>Creado</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($standards as $item)
                                <tr>
                                    <td><a href="{{ route('standards.show', $item) }}">{{$item->name}}</a></td>
                                    <td class="text-center">{{$item->aspects_count}}</td>
                                    <td>{{$item->created_at->format('d-m-Y')}}</td>
                                    <td><a data-toggle="tooltip" title="Editar" class="btn btn-sm btn-warning" href="{{ route('standards.edit', $item) }}"><i class="fa fa-edit"></i></a></td>
                                    <td><button data-toggle="tooltip" title="Eliminar" class="btn btn-sm btn-outline-danger" onclick="deleteItem('{{$item->slug}}')"><i class="fa fa-trash"></i></button></td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <form action="" method="post" id="form-delete-item">
        @csrf @method('DELETE')
    </form>
</div>
@endsection

@section('scripts')
    <script src="{{ asset('js/jquery-3.5.1.js') }}"></script>
    <script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#table-index').DataTable();
        } );
    </script>
    <script>
        function deleteItem(item)
        {
            swal({
                    title: "¿Eliminar registro?",
                    text: "¿Esta seguro que desea eliminar este registro?",
                    icon: "warning",
                    buttons: ['Cancelar','Eliminar'],
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        document.querySelector("#form-delete-item").action = window.location.origin + '/standards/' + item
                        document.querySelector("#form-delete-item").submit()
                    }
                })
        }
    </script>
@endsection

@section('styles')
    <link href="{{asset('css/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
@endsection

resources/views/standards/show.blade.php
@extends('layouts.app')

@section('icon')
    <i class="pe-7s-star icon-gradient bg-sunny-morning"></i>
@endsection

@section('title')
    Detalles del criterio
@endsection

@section('button_title')
    <a href="{{ route('standards.index') }}" type="button" data-toggle="tooltip" title="" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary" data-original-title="Regresar" aria-describedby="tooltip109285">
        <i class="fa fa-arrow-left"></i>
    </a>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('standards.index') }}">Lista de criterios</a></li>
    <li class="active breadcrumb-item" aria-current="page">Detalles del criterio</li>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card my-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 my-2">
                            <h3 class="text-capitalize">{{$standard->name}}</h3>
                        </div>
                        <div class="col-12 my-2 text-justify">
                            <p>{{$standard->description}}</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card my-2">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <h4>Agregar aspecto</h4>
                        </div>
                        <div class="col-12">
                            <form class="form-row" method="POST" action="{{ route('aspects.store') }}">
                                @csrf
                                <input type="hidden" name="standard_id" value="{{$standard->slug}}">
                                <div class="form-group col-lg-4">
                                    <label>Aspecto</label>
                                    <textarea name="description" required rows="3" class="form-control"></textarea>
                                </div>
                                <div class="form-group col-lg-3">
                                    <label>Calificación 1</label>
                                    <textarea name="min_rating" rows="3" class="form-control"></textarea>
                                </div>
                                <div class="form-group col-lg-3">
                                    <label>Calificación 5</label>
                                    <textarea name="max_rating" rows="3" class="form-control"></textarea>
                                </div>
                                <div class="form-group col-lg-1 text-center">
                                    <label>Limpiar</label>
                                    <button type="reset" class="btn btn-outline-danger"><i class="fa fa-times"></i></button>
                                </div>
                                <div class="form-group col-lg-1 text-center">
                                    <label>Agregar</label>
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card my-2">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <h4>({{$standard->aspects->count()}}) Aspectos</h4>
                        </div>
                        <div class="col-12">
                            @foreach ($standard->aspects as $aspect)    
                                <form method="POST" action="{{ route('aspects.update',$aspect) }}" class="form-row border-bottom border-primary p-2">
                                    @method('PUT')
                                    @csrf
                                    <div class="form-group col-lg-4">
                                        <label>Aspecto</label>
                                        <textarea name="description" required rows="3" class="form-control">{{$aspect->description}}</textarea>
                                    </div>
                                    <div class="form-group col-lg-3">
                                        <label>Calificación 1</label>
                                        <textarea name="min_rating" rows="3" class="form-control">{{$aspect->min_rating}}</textarea>
                                    </div>
                                    <div class="form-group col-lg-3">
                                        <label>Calificación 5</label>
                                        <textarea name="max_rating" rows="3" class="form-control">{{$aspect->max_rating}}</textarea>
                                    </div>
                                    <div class="form-group col-lg-1 text-center">
                                        <label>Actualizar</label>
                                        <button type="submit" class="btn btn-warning"><i class="fa fa-edit"></i></button>
                                    </div>
                                    <div class="form-group col-lg-1 text-center">
                                        <label>Eliminar</label>
                                        <button onclick="deleteItem('{{$aspect->id}}')" type="submit" class="btn btn-outline-danger"><i class="fa fa-trash"></i></button>
                                    </div>
                                </form>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <form action="" method="post" id="form-delete-item">
        @csrf @method('DELETE')
    </form>
@endsection

@section('scripts')
    <script>
        function deleteItem(item)
        {
            swal({
                    title: "¿Eliminar registro?",
                    text: "¿Esta seguro que desea eliminar este registro?",
                    icon: "warning",
                    buttons: ['Cancelar','Eliminar'],
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        document.querySelector("#form-delete-item").action = window.location.origin + '/aspects/' + item
                        document.querySelector("#form-delete-item").submit()
                    }
                })
        }
    </script>
@endsection